<?xml version="1.0" encoding="utf-8"?><Database Name="BudgetBuddy" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-CCUR4CG;Initial Catalog=BudgetBuddy;Integrated Security=True" SettingsObjectName="BudgetBuddy.Properties.Settings" SettingsPropertyName="BudgetBuddyConnectionString3" Provider="System.Data.SqlClient" />
  <Table Name="dbo.quest" Member="quests">
    <Type Name="quest">
      <Column Name="quest_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="quest_description" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="quest_reward" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="quest_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="quest_user_quest" Member="user_quests" ThisKey="quest_id" OtherKey="quest_id" Type="user_quest" />
    </Type>
  </Table>
  <Table Name="dbo.vouchers" Member="vouchers">
    <Type Name="voucher">
      <Column Name="voucher_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="voucher_name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="required_points" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="voucher_type" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="voucher_reward" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="voucher_user_voucher" Member="user_vouchers" ThisKey="voucher_id" OtherKey="voucher_id" Type="user_voucher" />
    </Type>
  </Table>
  <Table Name="dbo.quest_status" Member="quest_status">
    <Type Name="quest_status">
      <Column Name="status_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="status_name" Type="System.String" DbType="VarChar(55) NOT NULL" CanBeNull="false" />
      <Association Name="quest_status_user_quest" Member="user_quests" ThisKey="status_id" OtherKey="status_id" Type="user_quest" />
    </Type>
  </Table>
  <Table Name="dbo.transactions" Member="transactions">
    <Type Name="transaction">
      <Column Name="transaction_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="receiver_name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="sender_name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="transaction_type" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="transaction_name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="amount" Type="System.Decimal" DbType="Decimal(9,2) NOT NULL" CanBeNull="false" />
      <Column Name="transaction_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="users_bank_account_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="users_bank_account_transaction" Member="users_bank_account" ThisKey="users_bank_account_id" OtherKey="users_bank_account_id" Type="users_bank_account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.user_details" Member="user_details">
    <Type Name="user_detail">
      <Column Name="userDetails_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="first_name" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="last_name" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="profile_src" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="user_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="user_points" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="user_user_detail" Member="user" ThisKey="user_id" OtherKey="user_id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.user_quests" Member="user_quests">
    <Type Name="user_quest">
      <Column Name="user_quest_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="quest_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="date_completed" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="status_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="quest_user_quest" Member="quest" ThisKey="quest_id" OtherKey="quest_id" Type="quest" IsForeignKey="true" />
      <Association Name="quest_status_user_quest" Member="quest_status" ThisKey="status_id" OtherKey="status_id" Type="quest_status" IsForeignKey="true" />
      <Association Name="user_user_quest" Member="user" ThisKey="user_id" OtherKey="user_id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.user_voucher" Member="user_vouchers">
    <Type Name="user_voucher">
      <Column Name="user_voucher_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="voucher_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="voucher_user_voucher" Member="voucher" ThisKey="voucher_id" OtherKey="voucher_id" Type="voucher" IsForeignKey="true" />
      <Association Name="user_user_voucher" Member="user" ThisKey="user_id" OtherKey="user_id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.users" Member="users">
    <Type Name="user">
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="password_hash" Type="System.String" DbType="Char(64) NOT NULL" CanBeNull="false" />
      <Column Name="password_salt" Type="System.String" DbType="Char(64) NOT NULL" CanBeNull="false" />
      <Association Name="user_user_detail" Member="user_details" ThisKey="user_id" OtherKey="user_id" Type="user_detail" />
      <Association Name="user_user_quest" Member="user_quests" ThisKey="user_id" OtherKey="user_id" Type="user_quest" />
      <Association Name="user_user_voucher" Member="user_vouchers" ThisKey="user_id" OtherKey="user_id" Type="user_voucher" />
      <Association Name="user_users_bank_account" Member="users_bank_accounts" ThisKey="user_id" OtherKey="user_id" Type="users_bank_account" />
    </Type>
  </Table>
  <Table Name="dbo.users_bank_accounts" Member="users_bank_accounts">
    <Type Name="users_bank_account">
      <Column Name="users_bank_account_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="external_id" Type="System.String" DbType="Char(36) NOT NULL" CanBeNull="false" />
      <Column Name="account_type" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="users_bank_account_transaction" Member="transactions" ThisKey="users_bank_account_id" OtherKey="users_bank_account_id" Type="transaction" />
      <Association Name="user_users_bank_account" Member="user" ThisKey="user_id" OtherKey="user_id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
</Database>